insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('1','2021-11-17 16:09:11.047771','false','2021-11-17 16:09:11.047771','Phát triển tiếp kết quả của nhóm đề tài K16 để xây dựng được thư viện và module điều khiển bay cho quadcopter có khả năng tích hợp thêm các cảm biến và module giao tiếp khác.
Hiện thực được ứng dụng điều khiển 2-3 quadcopter hoạt động theo mô hình bầy đàn. 
','Liên hệ GVHD','2','1','{"en":" Developing A Flocking Control for a Swarm Drones","vi":" Phát triển mô hình điều khiển thiết bị bay theo cơ chế bầy đàn"}','Tìm hiểu kiến thức nền tảng về mô hình SWARM Robot (cụ thể cho drones) dựa trên báo cáo của nhóm sinh viên K16.
Tìm hiểu phần cứng và phương pháp điều khiển quadcopter (được cung cấp sẵn, sinh viên không phải thiết kế và hiện thực phần cứng robot)
Thực hiện các thử nghiệm trên mô hình phần cứng đã có để điều khiển.
Đề xuất các công việc sẽ thực hiện trong giai đoạn luận văn dựa trên cơ sở phát triển kết quả của nhóm đề tài K16.
','true',null,'4','1');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('2','2021-11-17 16:10:01.537353','false','2021-11-17 16:10:01.537353','Trong thời đại hiện nay, nhu cầu cần được giải trí của con người đang rất thịnh hành. Có khá nhiều loại hình giải trí cho con người, trong đó âm nhạc là một trong những sự lựa chọn phổ biến nhất. Tuy nhiên hiện nay, danh sách phát nhạc (playlist) thường được con người tạo ra bằng cách thêm những bài nhạc yêu thích của họ vào trong playlist. Do đó, trong đề tài này, nhóm đề xuất xây dựng một máy phát nhạc, có thể tự động tạo ra một playlist phát nhạc thông qua cảm xúc được thể hiện trên khuôn mặt của con người. Không những thế, người dùng còn có thể điều khiển trạng thái phát nhạc, cũng như lựa chọn bài hát trong playlist bằng giọng nói hoặc các hành động của cơ thể. Về máy phát nhạc, về phần cứng của nó là các board nhúng được tích hợp cùng với các mô hình học máy, học sâu để phục vụ cho mục đích của bài toán.',null,'3','1','{"en":"Developing An Emotional Music Player based on Facial Emotion Recognition","vi":"Thiết kế và hiện thực thiết bị phát nhạc thông qua cảm xúc khuôn mặt"}','Tìm hiểu các giải thuật về đồ họa máy tính, thị giác máy tính và học sâu được sử dụng trong bài toán Nhận diện cảm xúc khuôn mặt (facial emotion recognition).
Tìm hiểu về các board nhúng và các thiết bị ngoại vi cần dùng trong sản phẩm.
Tìm hiểu, xây dựng và phát triển phần cứng một máy nghe nhạc có kích thước phù hợp; kiểu dáng, mẫu mã đẹp; có năng suất như các máy nghe nhạc ngoài thị trường.
Tìm hiểu cách tích hợp các module học máy, học sâu vào các board nhúng
Thực hiện thử nghiệm và đánh giá tính khả thi của các thiết bị
Đề xuất mô hình và đặc tả chi tiết ứng dụng sẽ phát triển trong giai đoạn LVTN
','true',null,'4','1');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('3','2021-11-17 16:10:51.47219','false','2021-11-17 16:10:51.47219','Hiện thực một robot tự hành có khả năng tự tìm đường đến đích khi vận hành trong một môi trường không xác định','https://www.ros.org/
http://gazebosim.org/
Slam algorithms
https://github.com/Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots 
','3','1','{"en":"Path-planning problem for autonomous robot in the environment of uncertainly.","vi":"Tìm đường của robot tự hành trong môi trường không chắc chắn"}','Tìm hiểu về ROS, làm quen với mô phỏng trên Gazebo và TurtleBot 3, 
Tìm hiểu công nghệ Lidar, camera, giải thuật SLAM, và Plan-planning
Làm quen với OpenCV và CNN.
Tích hợp giải thuật tìm đường đi (đề xuất từ GV hướng dẫn) vào hệ thống mô phỏng robot (robot thật ở giai đoạn luận văn)
','true',null,'4','1');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('4','2021-11-17 16:11:24.937135','false','2021-11-17 16:11:24.937135','Hiện thực xe(robot) tự hành (prototype) có khả năng di chuyển theo tín hiệu đường và tránh vật cản di động.','Ros: https://www.ros.org/
Slam algorithms
http://gazebosim.org/
https://github.com/Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots 
','3','1','{"en":"Autonomous mobile ","vi":"Xe tự hành không người lái"}','Tìm hiểu về ROS, công nghệ Lidar, camera.
Làm quen với mô phỏng trên Gazebo, giải thuật SLAM, OpenCV, và CNN
Thử nghiệm hệ thống xe tự lái trên môi trường mô phỏng Gazebo tích hợp ROS.
','true',null,'4','1');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('5','2021-11-17 16:12:07.941267','false','2021-11-17 16:12:07.941267','	Robot mang theo drone tự hành, drone có khả năng cất cánh và hạ cánh xuống robot khi robot đang di chuyển. Ngoài ra drone còn có khả năng chụp ảnh và giao tiếp với robot chủ.','Ros: https://www.ros.org/
http://gazebosim.org/
Autonomous Landing of a UAV on a Moving Platform Using Model Predictive Control
','3','1','{"en":"Autonomous Landing of a Drone on a Moving Platform","vi":"Hỗ trợ drone (tự hành) hạ cánh trên sân di động  "}','Tìm hiểu về ROS, Drone, camera.
Làm quen với mô phỏng trên Gazebo
Thử nghiệm hệ thống trên môi trường mô phỏng Gazebo tích hợp ROS.
','true',null,'4','1');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('6','2021-11-17 16:12:49.483065','false','2021-11-17 16:12:49.483065','Drone có khả năng nhận diện và tracking vật thể di động','Ros: https://www.ros.org/
http://gazebosim.org/
https://github.com/Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots 
','3','1','{"en":"Object tracking by autonomous drone ","vi":"Drone tự hành bay theo quỹ đạo của vật thể xác định"}','Tìm hiểu về ROS, Drone, camera.
Làm quen với mô phỏng trên Gazebo
Thử nghiệm hệ thống trên môi trường mô phỏng Gazebo tích hợp ROS.
','true',null,'4','1');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('7','2021-11-17 16:13:35.479388','false','2021-11-17 16:13:35.479388','Xây dựng và triển khai hệ thống bảo mật dựa trên AI cho mạng máy tính dựa trên kiến trúc mạng định nghĩa bằng phần mềm. Để tăng hiệu suất của hê thống này, nền tảng NetFPGA-Sume, một nền tảng mới nhất của thiết kế mạng tốc độ cao 10G, sử dụng ngôn ngữ cấp cao để thiết kế, tổng hợp phần cứng nhanh hơn (HLS).
','Liên hệ GVHD','3','2','{"en":"AI-based security Deployment for Software Defined Network (SDN) on NetFPGA-SUME","vi":"Triển khai hệ thống bảo mật dựa trên AI cho mạng định nghĩa phần mềm SDN trên NetFPGA-SUME"}','Giai đoạn đề cương:
Tìm hiểu về kiến trúc mạng định nghĩa phần mềm (SDN), các giao thức cơ bản của OpenFlow
Tổng hợp các thuật toán AI liên quan bảo mật về phát hiện xâm nhập mạng dựa trên các dấu hiệu bất thường. Bên cạnh đó, đưa ra các tập dữ liệu phù hợp với môi trường hệ thống.Lựa chọn giải thuật AI và tập dữ liệu phù hợp.
Nghiên cứu thiết bị phần cứng hỗ trợ, phần mềm giả lập khả cấu hình NetFPGA-SUME
Giai đoạn luận văn:
Mô phỏng và hiện thực các cấu trúc cơ bản của hệ thống mạng SDN với phần cứng hỗ trợ NetFPGA-SUME. 
Kiểm thử hệ thống đề xuất hoạt động giữa hai lớp điều khiển Controller và lớp dữ liệu dataplane. 
Kiểm thử các đề xuất về thuật toán AI và tập dữ liệu trên phần mềm.
Hiện thực mô hình kiểm thử ở phần mềm lên phần cứng nhằm tích hợp hệ thống bảo mật cho SDN.
Xây dựng mô hình kiểm thử hệ thống đề xuất thiết kế, và hoàn chỉnh hệ thống
','true',null,'4','5');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('8','2021-11-17 16:15:53.484501','false','2021-11-17 16:15:53.484501','Smart parking is an important element in the development of smart cities. This project aims at designing and implementing a hardware/software co-design architecture for accelerating AI algorithms in Edge Computing platforms such as FPGA or System-on-chip (SoC), thereby applying to smart parking environment.','K. Hassoune, W. Dachry, F. Moutaouakkil and H. Medromi, "Smart parking systems: A survey," 2016 11th International Conference on Intelligent Systems: Theories and Applications (SITA), 2016, pp. 1-6, doi: 10.1109/SITA.2016.7772297.
Li, Wenbin & Liewig, Matthieu. (2020). A Survey of AI Accelerators for Edge Environment. 10.1007/978-3-030-45691-7_4.
','3','3','{"en":"An Edge AI Hardware Acceleration Solution for Smart Parking Environment","vi":null}','  Phase 1: Pre-Thesis 
Study about Smart Parking, Edge Computing, and their roles in Smart Cities.
Do a literature review about existing smart parking solutions and related technologies.
Do a literature review and tool exploration about Edge AI platforms (FPGA or SoC) satisfied with Smart Parking environment.
Study on Edge AI Hardware Acceleration techniques and technologies, which can be used in Smart Parking systems.
Study on AI algorithms for Smart Parking tasks: 
Determine the number of parked vehicles and empty parking spaces in a parking lot from surveillance cameras.
Detect parking lots line or region of interest (ROI) 
Build a real-time license plate detection solution for parking access
Do experiments to exploit the existing solutions.
  Phase 2: Thesis
Design and implement an Edge AI Hardware Acceleration solution for Smart Parking tasks.
Integrate the Edge AI solution with Cloud Server and User Applications
Implement testbed to test the proposed system.
Evaluate performance and deploy the system in practical environment.  
','true',null,'4','5');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('9','2021-11-17 16:16:57.523767','false','2021-11-17 16:16:57.523767','Xây dựng môi trong mô phỏng cho việc truyền nhận dữ liệu LoRa, đo đạc các thông số liên quan đến năng lượng, thời gian hoạt động, đụng độ dữ liệu, mô phỏng năng lượng mặt trời cho việc cấp nguồn của hệ thống.
Hiện thực một ứng dụng thử nghiệm việc giao tiếp giữa các nốt LoRa thật để đối chiếu với môi trường mô phỏng
','Liên hệ GVHD','2','1','{"en":"Develop LoRa Mesh Simulation Environment on OMNET++","vi":"Xây dựng môi trường mô phỏng LoRa Mesh trên OMNET++"}','Tìm hiểu công cụ mô phỏng OMNET++
Tìm hiểu kĩ thuật gửi nhận dữ liệu không dây trên OMNET++
Hiện thực mô hình mô phỏng giao tiếp LoRa
Hiện thực mô hình mô phỏng năng lượng 
Đề xuất mô hình và đặc tả chi tiết ứng dụng sẽ phát triển trong giai đoạn LVTN
','true',null,'4','1');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('10','2021-11-17 16:17:32.663316','false','2021-11-17 16:17:32.663316','Đối với giao tiếp LoRa, mặc dù có lợi thế trong việc giao tiếp xa, nhưng dữ liệu trong gói tin LoRa là hạn chế về kích thước do vấn đề năng lượng của kênh truyền. Do đó, các bài toán liên quan đến xử lý ảnh (computer vision) cần phải được xử lý tại biên trước khi gửi kết quả về Gateway.',null,'2','1','{"en":"Edge Computing Applied for LoRa based Application","vi":"Tính toán biên cho một ứng dụng dựa trên LoRa"}','Tìm hiểu mạng cảm biến sử dụng giao tiếp LoRa
Tìm hiểu các thiết bị camera có thể áp dụng cho bài toán xử lý ảnh
Tìm hiểu các model AI có thể áp dụng vào hệ thống có tài nguyên hạn chế
Hiện thực thử nghiệm bài toán nhận điện bằng AI Model
Đề xuất ứng dụng sẽ thực hiện trong giai đoạn luận văn 
','true',null,'4','1');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('11','2021-11-17 16:19:13.001399','false','2021-11-17 16:19:13.001399','Nhu cầu và xu hướng tất yếu trong vấn đề theo dõi sức khỏe từ xa là tất yếu trong hiện tại cũng như tương lai. Hai chỉ số Oxy máu và ECG là các chỉ số sức khỏe quan trọng trong tầm soát và tiên đoán những dấu hiệu về sức khỏe cần có sự can thiệp của bác sĩ.
Hiện thực hệ thống theo dõi 2 chỉ số Oxy máu và ECG trực tuyến (online) và từ xa (remote) sẽ đem đến nhiều giá trị thực tiễn về cả lĩnh vực y tế và đóng góp trong mảng tích hợp công nghệ vào đời sống, sức khỏe cộng đồng.
','Liên hệ GVHD','3','3','{"en":"Online Blood oxygen and ECG monitoring system.","vi":"Thiết kế và chế tạo thiết bị theo dõi Oxy máu và ECG online."}','Tìm hiểu kiến thức nền tảng về Oxy máu và ECG cơ bản.
Tìm hiểu phần cứng và phương pháp giao tiếp với các hệ thống cảm biến, thiết bị chuyên dụng đo Oxy máu, ECG.
Thực hiện các thử nghiệm trên mô hình phần cứng đã có để khảo sát, đánh giá, tiền xử lý dữ liệu.
Xây dựng mô hình ứng dụng, và kịch bản ứng dụng cơ bản đo Oxy máu và ECG online.
','true',null,'4','1');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('12','2021-11-17 16:18:12.250712','false','2021-11-17 16:18:12.250712','Đối với ứng dụng chăm sóc sức khỏe hiện tại, hệ thống nhận diện khuôn mặt đóng vai trò then chốt đối với hệ thống. Luận văn hướng đến việc cải tiến hệ thống nhận diện khuôn mặt hiện tại, nâng cao độ chính xác với các giải pháp phần mềm lẫn phần cứng.',null,'2','1','{"en":"Improve face recognition system in eHealth application","vi":"Cải tiến hệ thống nhận dạng khuôn mặt trong ứng dụng sức khỏe điện tử"}','Tìm hiểu hệ thống nhận dạng khuôn mặt trên Jetson Nano
Chạy ứng dụng nhận diện khuôn mặt
Đề xuất các cơ chế cải tiến
Hiện thực thử nghiệm 
Đề xuất ứng dụng sẽ thực hiện trong giai đoạn luận văn 
','true',null,'4','1');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('13','2021-11-17 16:20:02.222099','false','2021-11-17 16:20:02.222099','Đề tài tập trung vào phân tích mã nguồn của Openpiton RISC-V SoC để tìm các lỗ hỏng bảo mật mức phần cứng và đề xuất các giải pháp khắc phục',null,'3','1','{"en":"RISC-V SoC HW security testing with HDL analysis","vi":"Kiểm thử bảo mật phần cứng của RISC-V SoC bằng việc phân tích mã nguồn RTL"}','Dựng lại môi trường mô phỏng của openpiton.
Đọc và phân tích Verilog source code, từ đó dựng lại block diagram cho toàn bộ SoC và cho từng module của hệ thống.
Đào sâu vào từng module để tìm những lỗ hổng trong hiện thực phần cứng. Nếu tìm thấy lỗ hổng:
Dựng testbench để chứng minh lỗ hổng tìm được.
Viết user application bằng C để khai thác lỗ hổng từ phần mềm.
Đánh giá độ nguy hiểm của lỗi.
Đưa ra đề xuất để vá những lỗi tìm được, có thể đưa ra những tình huống mà lỗi có thể xảy ra trong thực tế
Tổng hợp lại về hardware bugs, hardware attack patterns, ...
','true',null,'4','1');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('14','2021-11-17 16:20:51.562302','false','2021-11-17 16:20:51.562302','Đề tài tập trung vào tìm hiểu và phân tích mạng nơ-ron học sâu và đề xuất phương pháp tăng tốc độ xử lý giai đoạn suy luận (inference) bằng cách kết hợp phần cứng tái cấu hình FPGA với các bộ xử lý truyền thống. Đề tài tập trung vào việc phát triển lõi tính toán phục vụ cho việc xử lý mạng nơ-ron trên FPGA đồng thời phát triển hệ thống SoC kết hợp phần cứng phần mềm để thực thi hệ thống và đo đạc số liệu liên quan đến hiệu suất.',null,'3','2','{"en":"RISC-V SoC HW security testing with HDL analysis","vi":"Tăng tốc mạng nơ-ron học sâu với phần cứng tái cấu hình"}','Tìm hiểu mạng nơ-ron CNN.
Phân tích hoạt động tìm hiểu các model phù hợp cho các nền tảng phần cứng tái cấu hình/điện toán biên
Phát triễn lõi tính toán (core) phù hợp cho việc tăng tốc mạng nơ-ron
Xây dựng hệ thống SoC kết hợp phần cứng FGPA và phần mềm trên CPU
Phát triển ứng dụng kiểm thử
Đo đạc và tính toán hiệu suất xử lý.
','true',null,'4','1');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('15','2021-11-23 23:11:17.794345','false','2021-11-23 23:11:17.794345','<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Leveraging blockchain technology in validating, storing and managing the work history of individuals. The main idea is to write down to an underlying shared ledger blockchain to keep track when a person graduated, obtained a certificate, joined / left a company or got promoted. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>','<p>Ethereum yellow paper: https://ethereum.github.io/yellowpaper/paper.pdf<br>Solidity: https://docs.soliditylang.org/en/v0.8.7/&nbsp;</p>','2','1','{"en":"A Blockchain-Enabled Platform for Certifying Employee Résumés","vi":"Nền tảng chứng thực lý lịch làm việc dùng chuỗi khối"}','<p>Constructing a blockchain database for storing each individuals work record.<br>Launching a mobile application for individuals to manage their own achievements.<br>Releasing a web portal for enterprises to keep track of the promotion of their own employees.<br>Provide an open API for the certification of employees’ work history.<br>Package the blockchain program (Docker image) for the business party wishing to store the entire blockchain directly.</p>'
,'true',null,'4','2');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('16','2021-11-23 23:14:28.775785','false','2021-11-23 23:14:28.775785','<p>OISP is currently in need of a digital initiative to monitor the social work program undertaken by its undergraduate students. A student must undertake a certain amount of social work and accumulated a designated number of credits to be able to graduate. This digital attempt allows the undergraduate students to register their social work jobs and check if they really show up to get the job done. Such a portal also facilitates the management of the social work program from the administrative perspective.</p>','<p>Liên hệ GVHD</p>','3','1','{"en":"A Web portal for monitoring the social work program at OISP","vi":"Cổng thông tin số hóa việc thực hiện ngày công tác xã hội tại OISP"}','<p>Nghiên cứu các kiến trúc hệ thống microservices.&nbsp;<br>Thiết kế hệ thống các services theo kiến trúc microservices.&nbsp;<br>Thiết kế giao diện và các giải pháp số hoá cổng thông tin ngày công tác xã hội OISP.&nbsp;<br>Xây dựng hệ thống số hoá các hoạt động và chuỗi hoạt động và đăng ký tham gia các hoạt động ngoại khoá.&nbsp;<br>Xây dựng mô đun truy xuất và phân tích dữ liệu từ các hoạt động và đưa ra các gợi ý cho việc tổ chức hoạt động hiệu quả.<br>Xây dựng mô đun điểm danh bằng cách sử dụng vị trí thời gian thực và ứng dụng nhận diện khuôn mặt.&nbsp;<br>Xây dựng ứng dụng di động cho cổng thông tin công tác xã hội OISP và ứng dụng web cho việc quản lý và truy xuất dữ liệu.&nbsp;<br>Tối ưu hoá hệ thống bằng cách sử dụng caching và message queue cho các services chịu tải lớn.<br>Triển khai hệ thống và kiểm định khả năng sử dụng trong thực tế.</p>'
,'true',null,'4','3');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('17','2021-11-23 23:15:32.996545','false','2021-11-23 23:15:32.996545','<p>Messaging utilities are essentially part of many collaborative work systems in use today. With the rise of software bots and computer graphics, end-users and software developers expect to enjoy lightweight yet fancy chatting services for various purposes. In this thesis, we investigate an open architecture following which a centralized messaging module might be developed. An effective database system, techniques for implementing a conversational assistant and a Web interface facilitating message delivery should be considered in this work.</p>','<p>Liên hệ GVHD</p>','3','1','{"en":"An Open Architecture for Centralized Message Delivery","vi":"Nền tảng trao đổi tinh nhắn nhanh theo kiến trúc có tính mở"}','<p>- Xây dựng hệ thống cơ sở dữ liệu phục vụ cho việc lưu trữ thông tin chat và người dùng.<br>- Xây dựng phương thức kết nối an toàn cho mục đích trao đổi tin nhắn.<br>- Xây dựng giao diện website đáp ứng được nhu cầu đăng nhập, cập nhập thông tin, theo dõi tin nhắn và lịch sử tin nhắn.<br>- Xây dựng hệ thống phân tích và tự động phản hồi tin nhắn sử dụng các kĩ thuật phân tích ngôn ngữ tự nhiên.</p>'
,'true',null,'4','4');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('18','2021-11-23 23:17:16.094668','false','2021-11-23 23:17:16.094668','<p>Spelling and grammar mistakes are quite common in people writing essays, emails, reports and in daily conversations. &nbsp;These mistakes might lead to severe consequences, such as misunderstanding or even cause the reader to feel irritated. Currently, some popular spell checking tools exist but can only support English. Hence, the need for a tool to tackle this problem in the Vietnamese language is significant and in high demand.</p><p>The goal of this project is to develop a system that could analyse and correct spelling and grammar mistakes with the use of Machine Learning model, while also providing an efficient way of text preprocessing for various NLP models.</p>',null,'3','1','{"en":"Building a browser-integrated system for correcting Vietnamese spelling and grammar.","vi":""}','<p>Prepare training data.<br>Research Vietnamese spell and grammar correction models.<br>Develop a complete system.<br>Testing and evaluating the systems accuracy.<br>Develop a plugin demo.</p>'
,'true',null,'4','2');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('19','2021-11-23 23:22:29.301604','false','2021-11-23 23:22:29.301604','<p>The number of news published everyday is nearly uncountable. Due to the explosion of social media where users frequently share content just by clicking some buttons, the information spreads quickly. People then may be misled to fake news or too believe in news that has not been verified. Hence, the reliability and credibility of both the information source and information itself have emerged as a global issue in contemporary society [1]. The exposed consequence of trusting fake news on the Internet has been clearly shown in the middle COVID-19 pandemic, which results in negative behavioral change.. Furthermore, anti-vaccine information and fake COVID-19 treatment can cause serious danger to public health [2,3]. It is not an overstatement to say that currently combating fake news is as important as treating COVID-19.<br>In this project, a Machine Learning model will be built in order to evaluate news sources whether it is verified, unverified or fake and applied to a web browser extension for usage afterward. During the development process, an automated Machine Learning service will also be implemented for collecting data as well as training the model automatically.</p>','<p>[1] Zha, X., Yang, H., Yan, Y., Liu, K., &amp; Huang, C. (2018). Exploring the effect of social media information quality, source credibility and reputation on informational fit-to-task: Moderating role of focused immersion. Computers in Human Behavior, 79, 227-237.<br>[2] Greene, C., &amp; Murphy, G. (2020). Can fake news really change behaviour? Evidence from a study of COVID-19 misinformation.<br>[3] Germani, F., &amp; Biller-Andorno, N. (2021). The anti-vaccination infodemic on social media: A behavioral analysis. PloS one, 16(3), e0247642.</p>','3','1','{"en":" Evaluation of news sources using Machine Learning and its application to a web browser extension.","vi":null}','<p>Find out the criteria to spot fake news.<br>Research on Machine Learning models on fake news detection.<br>Collect, create and manage a database storing verified news and fake news for training.<br>Create a web scraper to collect news.<br>Apply the model in a web browser extension.<br>Create an automated pipeline for deployment.<br>Develop a demo.</p>'
,'true',null,'3','3');
insert into tp_topic(created_at,deleted,updated_at,description,document_reference,max_student_take,min_student_take,name,task,thesis,council_id,semester_id,subject_department_id) values('20','2021-11-23 23:24:00.740587','false','2021-11-23 23:24:00.740587','<p>Vấn đề về giám sát phương tiện di chuyển qua lại trên các đoạn đường hiện đang là một trong những vấn đề phổ biến và cấp thiết đối trong cuộc sống. Có khá nhiều ứng dụng cho vấn dề này như: phát hiện người vi phạm giao thông, quản lý số lượng các phương tiện di chuyển, tính toán mật độ tham gia giao thông,.v..v.. Hệ thống xây dựng trong đề tài này hướng tới việc giám sát các phương tiên qua lại với đầu vào là video trực tiếp từ camera giám sát. Các thông tin về thời gian di chuyển, biển số xe của phương tiện sẽ được hệ thống detect sau đó được lưu trữ lại để phục vụ cho các nhu cầu trong thực tế như: quản lý các biển số của người dân sử dụng trong khu vực, các phương tiên không đủ tiêu chuẩn tham gia giao thông.</p>','<p>Liên hệ GVHD</p>','2','1','{"en":null,"vi":"Hệ thống giám sát phương tiện qua lại"}','<p>Xây dựng module detect phương tiện di chuyển<br>Xây dựng module detect biển số<br>Deploy web server thu thập và hiển thị dữ liệu<br>Cải thiện độ chính xác, tốc độ, tính áp dụng thực tế của ứng dụng</p>'
,'true',null,'4','4');
